In [61]:
import numpy as np 

board = np.full((3,3), 'null')
board_init = np.reshape(np.arange(1,10), (3,3))

In [81]:
board

array([['null', 'X', 'null'],
       ['X', 'O', 'null'],
       ['null', 'null', 'null']], dtype='<U4')

In [66]:
board[np.where(board_init==4)] = 'X'

In [80]:
board[0,1] = 'X'

In [98]:
board [:,0]

array(['null', 'X', 'null'], dtype='<U4')

In [53]:
inp = input('Input: ')
int(inp)

Input: 5


5

In [67]:
board[np.where(board_init==9)] == np.array('null')

array([ True])

In [68]:
board[np.where(board_init==4)] == np.array('X')

array([ True])

In [69]:
print(board)

[['null' 'null' 'null']
 ['X' 'null' 'null']
 ['null' 'null' 'null']]


In [14]:
from pprint import pprint

In [15]:
pprint(board)

array([[       47566960,        47807664, 139941116936408],
       [139940128382312, 139941110234056, 139941173549296],
       [139940745940752, 139941173078032,              80]])


In [72]:
from itertools import permutations
list(permutations([0,1,2]))

[(0, 1, 2), (0, 2, 1), (1, 0, 2), (1, 2, 0), (2, 0, 1), (2, 1, 0)]

In [108]:
np.array('X').item(0)

'X'

In [110]:
if np.array('X') == np.array('X'): 
    print ('yes')

yes


In [ ]:
i